### ISSUE TITLE
Time forfeits in uncountable quantity

### ISSUE THREAD

**Issue by SzotsGabor** [Dannyj1/Zagreus#46]
Hi Danny,

In my last tournament for Zagreus 2.2.0 there were 192 time forfeits out of 576 games! I don't know if they all were caused by Zagreus but I suspect so.
Have you not noticed that before? Does 2.3.0 solve the problem?

I used Arena. Time control was 1.6 minutes + 0.8 seconds. Maybe Zagreus does not understand split seconds increment?

**Comment by Dannyj1** [comment]
Thanks for reporting this!

I have actually been working on the time forfeit issue + some crashes in very long-lasting games for the past few days. I am currently testing some of the recent changes to time management to see if the issues are fully gone.

Unfortunately, this issue is not solved in 2.3.0. I am looking to release the fix in the next few days if everything goes well. I will keep you updated.

**Comment by Dannyj1** [comment]
I managed to get the amount of time forfeits down to about 1% of the games played at 1 minutes + 0.6 seconds, but that is still too much in my opinion. Would preferably have 0 timeouts. Will need to take a bit more time to get this fixed.

**Comment by Dannyj1** [comment]
The latest release had only 3 time forfeits over 1156 matches played on 3 different machines. The time forfeits only occured on one machine.

I have released this fix in v2.3.1. If for whatever reason the time forfeits happen again, feel free to re-open this issue.

Thanks again for reporting this!
