### ISSUE TITLE
v2.4 out ?

### ISSUE THREAD

**Issue by tissatussa** [Dannyj1/Zagreus#53]
i just compiled the latest source by `git clone` and i see the `uci` command shows v2.4, however your GitHub page shows v2.3.1 being the latest version.

is v2.4 a development version ?
latest edit was 2 months ago ..

**Comment by Dannyj1** [comment]
v2.4 is still a development version. Anything in the master branch is a development version, but well tested and has an ELO increase over an older version in self-play. The latest actual release is always the one on the releases page and the source related to this version is tagged.

It might be a better idea to use a different branch for the development version instead of master.

I have been a bit busy recently, so haven't been able to work on the next release. I am working on a big evaluation rewrite, so it might take a while to finish this update.

Hopefully this clarifies everything, if not feel free to reply :)

**Comment by tissatussa** [comment]
Thanks for this explanation. You can also put a version number like "v2.4-dev" or even "v2.4-dev 987654321", shown by the `uci` command. This method is used by some authors of (GitHub) chess engines.

**Comment by Dannyj1** [comment]
I do actually have a system like this, but it only appends <branch name>-<commit hash> when not in the master branch. I do think a separate dev branch is the most clear to those who want to compile from source.
